# fly.toml app configuration file generated for h-userbot on 2023-10-19T00:08:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "h-userbot"
primary_region = "waw"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
